"""Generate a clearly synthetic, reproducible image-audit demonstration."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from scipy.ndimage import gaussian_filter

from research.image_audit_report import analyse


def build(output: Path) -> None:
    if output.exists():
        raise FileExistsError("Use a new demo directory")
    output.mkdir(parents=True)
    y, x = np.indices((128, 128))
    rng = np.random.default_rng(20260917)
    field = np.sin(x / 8.0) + np.sin(y / 11.0) + 0.25 * rng.normal(size=(128, 128))
    image = gaussian_filter(field, 1.25)
    np.save(output / "synthetic_grayscale.npy", image)
    manifest = dict(
        source="SYNTHETIC DEMO — generated patterns, not alloy micrographs",
        license="Synthetic demonstration generated by this repository",
        phase_definition="Pixels above a declared grayscale threshold; no real phase identity",
        records=[dict(
            id="synthetic-01", path="synthetic_grayscale.npy",
            roi=[16, 112, 16, 112],
            roi_reason="Fixed interior field, declared before measuring",
            thresholds=[-0.2, 0.0, 0.2],
            threshold_reason="Symmetric illustrative grayscale sensitivity range",
            foreground="above", preview_threshold=0.0,
            pixel_size=1.0, length_unit="synthetic pixels",
        )],
    )
    manifest_path = output / "input.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    analyse(manifest_path, output / "audit", include_previews=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    build(args.output)
